name: Instafel CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build instafel.website
      run: |
        ./gradlew :instafel.website:install
        ./gradlew :instafel.website:build

    - name: Build instafel.gplayapi
      run: |
        ./gradlew :instafel.website:build-jar

    - name: Build instafel.updater
      run: |
        ./gradlew :instafel.updater:generate-app-debug

    - name: Build instafel.app
      run: |
        ./gradlew :instafel.app:generate-app-debug
